# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "rockylinux/9"
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 3000
    end
  
    config.vm.define "ns01" do |ns01|
      ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
      ns01.vm.hostname = "ns01"
      ns01.ssh.insert_key = false
    end
  
    config.vm.define "client" do |client|
      client.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "dns"
      client.vm.hostname = "client"
      client.ssh.insert_key = false
    end

    config.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvv"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.limit = "all"
    end
  
  end